name: Build and run tests
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v4
            - name: Setup JDK 21
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: 21
            - name: Setup gradle
              uses: gradle/actions/setup-gradle@v3
            - name: build
              run: ./gradlew build --info
