name: Build and run tests
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v4

            - name: Setup JDK 21
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: 21

            - name: Setup gradle
              uses: gradle/actions/setup-gradle@v3

            - name: Create Docker network
              run: docker network create cassandra-network

            - name: Start Cassandra node 1
              run: |
                docker run -d --name cassandra-node1 \
                  --network cassandra-network \
                  -p 9042:9042 \
                  -e CASSANDRA_CLUSTER_NAME=TestCluster \
                  -e CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch \
                  -e CASSANDRA_DC=datacenter1 \
                  cassandra:latest

            - name: Get node 1 IP
              run: |
                NODE1_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' cassandra-node1)

            - name: Start Cassandra node 2
              run: |
                docker run -d --name cassandra-node2 \
                --network cassandra-network \
                -e CASSANDRA_SEEDS=${NODE1_IP} \
                -e CASSANDRA_CLUSTER_NAME=TestCluster \
                -e CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch \
                -e CASSANDRA_DC=datacenter1 \
                cassandra:latest

            - name: Wait for nodes to join
              run: |
                sleep 60

            - name: Run CQL scripts
              run: |
                  docker exec -i cassandra-node1 cqlsh -f schema.cql

            - name: build
              run: ./gradlew build --info
